routes/web.php
<?php

use Bittacora\Page\Http\Controllers\PageController;
use Bittacora\Page\Http\Controllers\PublicPageController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Schema;

Route::prefix('bpanel')->middleware(['web', 'auth', 'admin-menu'])->name('page.')->group(function(){
    Route::get('page', [PageController::class, 'index'])->name('index');
    Route::get('page/{page}/show', [PageController::class, 'show'])->name('show');
    Route::get('page/create/language/{locale?}', [PageController::class, 'create'])->name('create');
    Route::post('page/store', [PageController::class, 'store'])->name('store');
    Route::get('page/{model}/edit/language/{locale?}', [PageController::class, 'edit'])->name('edit');
    Route::put('page/{model}/update/language/{locale?}', [PageController::class, 'update'])->name('update');
    Route::delete('page/{page}', [PageController::class, 'destroy'])->name('destroy');
    Route::post('page/reorder', [PageController::class, 'reorder'])->name('reorder');
    Route::get('page/multimedia', [PageController::class, 'multimedia'])->name('multimedia');
});

Route::middleware(['web'])->name('publicPage.')->group(function(){
    Route::get(__('general.page-slug').'/{slug}', [PublicPageController::class, 'show'])->name('show');
});

resources/views/create.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Crear página')

@section('content')
    <p class="alert alert-success">
        {!!  __('page::page.create_default_language') !!}
    </p>
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0 d-flex justify-content-between">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('page::page.add') }}</span>
            </h4>
            <img src="{{asset('img/flags/'.$language.'.png')}}" alt="{{ $language }}">
        </div>

        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('page.store')}}" enctype="multipart/form-data">
            @csrf
            @livewire('form::input-text', ['name' => 'title', 'labelText' => __('page::page.title'), 'required'=>true])
            @livewire('utils::tinymce-editor', ['name' => 'long_text', 'labelText' => __('page::page.long_text')])
            @livewire('utils::tinymce-editor', ['name' => 'short_text', 'labelText' => __('page::page.short_text')])
            @livewire('form::input-checkbox', ['name' => 'active', 'value' => 1, 'labelText' => __('page::page.active'), 'bpanelForm' => true, 'checked' => true])
            @livewire('form::input-checkbox', ['name' => 'include_team', 'value' => 1, 'labelText' => __('page::page.include_team'), 'bpanelForm' => true, 'checked' => false])
            @livewire('content-multimedia::upload-content-multimedia-widget', ['model' => null, 'allowedFormats' => $allowedFormats, 'allowedExtensions' => $allowedExtensions])
            @livewire('seo::seo-fields')


            <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
                @livewire('form::save-button',['theme'=>'save'])
                @livewire('form::save-button',['theme'=>'reset'])
            </div>
            @livewire('form::input-hidden', ['name' => 'locale', 'value'=> $language])
        </form>
        @livewire('multimedia::multimedia-images-library')
    </div>
@endsection

resources/views/edit.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Editar página')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0 d-flex justify-content-between">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('page::page.edit') }}</span>
            </h4>
            @include('language::partials.form-languages', ['model' => $page, 'edit_route_name' => 'page.edit',  'currentLanguage' => $language])
        </div>

{{--  ###      @livewire('utils::media-library')--}}
        <form class="mt-lg-3" autocomplete="off" method="post" action="{{ route('page.update', ['model' => $page, 'locale' => $language]) }}" enctype="multipart/form-data">
            @csrf
            @livewire('form::input-text', ['name' => 'title', 'labelText' => __('page::page.title'), 'required'=>true, 'value' => $page->title])
{{--  ###            @livewire('form::input-text', ['name' => 'subtitle', 'labelText' => __('page::page.subtitle'), 'required'=>false, 'value' => $page->subtitle])--}}
            @livewire('utils::tinymce-editor', ['name' => 'long_text', 'labelText' => __('page::page.long_text'), 'value' => $page->long_text])
            @livewire('utils::tinymce-editor', ['name' => 'short_text', 'labelText' => __('page::page.sidebar'), 'value' => $page->short_text])
            @livewire('form::input-checkbox', [
            'name' => 'active',
            'value' => 1,
            'labelText' => __('page::page.active'),
            'bpanelForm' => true,
            'checked' => $page->active == 1,
            ])

            @livewire('form::input-checkbox', [
            'name' => 'include_team',
            'value' => 1,
            'labelText' => __('page::page.include_team'),
            'bpanelForm' => true,
            'checked' => $page->include_team == 1,
            ])
            @livewire('content-multimedia::upload-content-multimedia-widget', ['model' => $page, 'allowedFormats' => $allowedFormats, 'allowedExtensions' => $allowedExtensions])
            @livewire('content-multimedia-images::content-multimedia-images-widget', ['module' => 'page', 'contentId' => $page->content->id, 'permission' => 'page.edit'])
{{--  ###            @livewire('content-multimedia-documents::content-multimedia-documents-widget', ['contentId' => $page->content->id, 'permission' => 'page.edit'])--}}
{{--  ###            @livewire('content-multimedia-links::content-multimedia-links-widget', ['contentId' => $page->content->id, 'permission' => 'page.edit'])--}}
            @livewire('seo::seo-fields', ['model' => $page])


            @livewire('utils::created-updated-info', ['model' => $page])

            <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
                @livewire('form::save-button',['theme'=>'save'])
                @livewire('form::save-button',['theme'=>'reset'])
            </div>
            @livewire('form::input-hidden', ['name' => 'locale', 'value'=> $language])
            @livewire('form::input-hidden', ['name' => 'id', 'value'=> $page->id])
            <input type="hidden" name="_method" value="PUT">
        </form>
        @livewire('multimedia::multimedia-images-library')
    </div>
@endsection

resources/views/index.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Páginas de contenido')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('page::page.page_list') }}</span>
            </h4>
        </div>
        <div class="card-body">
            @livewire('page::page-datatable')
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('assets_bpanel/js/livewire-sortable.js') }}"></script>
@endpush

resources/views/livewire/datatable-checkbox.blade.php
<div class="form-check form-check-inline">
    <input class="form-check-input ace-switch input-sm"
           type="checkbox"
           @if($multiple) name="{{$name}}[]" @else name="{{$name}}" @endif
           id="{{$idField}}"
           wire:click="toggle({{$idField}})"
           @if($checked==1) checked @endif
    >
    @if(!is_null($labelText))
        <label class="form-check-label" for="{{$idField}}">{{ $labelText }}</label>
    @endif
</div>

resources/views/livewire/page-datatable.blade.php
<td>
    {{$row->title}}
</td>
<td>
    @livewire('language::datatable-languages', ['model' => $row, 'createRouteName' => 'page.edit', 'editRouteName' => 'page.edit'], key('page-language-'.$row->id))
</td>
<td>
    @livewire('utils::datatable-default', ['fieldName' => 'active', 'model' => $row, 'value' => $row->active, 'size' => 'xxs'], key('active-page-'.$row->id))
</td>
<td>
    <div class="d-flex justify-content-center align-items-center">
        <span class="align-items-center badge bgc-purple-d1 pos-rel text-white radius-4 px-3">
            <span class="bgc-primary-tp4 opacity-5 position-tl h-100 w-100 radius-4"></span>
            <span class="pos-rel">
                {{$row->order_column}}
            </span>
        </span>
    </div>
</td>
<td>
    @livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'page', 'model' => $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'la página?'], key('page-buttons-'.$row->id))
</td>

resources/views/partials/actions.blade.php
<div class="action-buttons">
    <a class="text-blue mx-2" href="{{route($scope.'.show',$id)}}">
        <i class="fa fa-search"></i>
    </a>
    <a class="text-success mx-2" href="{{route($scope.'.edit', $id)}}">
        <i class="fa fa-pencil"></i>
    </a>
    <form method="POST" class="d-inline mx-2"
          action="{{route($scope.'.destroy', $id)}}">
        {!!method_field('DELETE')!!}
        @csrf
        <button id="delete_button{{$id}}" type="submit" class="btn btn-primary-outline text-danger"
                @if($disabled) disabled @endif
                onclick="return confirm('¿Está seguro de querer borrar {{$message}}')">
            <i class="fa fa-trash"></i>
        </button>
    </form>
</div>

resources/views/partials/active.blade.php
<div class="text-center">
    @livewire('page-datatable-checkbox',[
    'idField' => $idField,
    'name' => $name,
    'checked' => $checked,
 ])
</div>

resources/views/partials/default.blade.php
<div class="text-center">
    @livewire('page-datatable-default',[
    'idField' => $idField,
    'name' => $name,
    'value' => $value,
 ])
</div>